apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-test
  labels:
    app: match-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-test
  template:
    metadata:
      labels:
        app: match-test
    spec:
      containers:
        - name: match-test
          image: skcc03.azurecr.io/match-test:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5